"""Add release_time and cost to Booking model

Revision ID: 2edd11789cc2
Revises: 2e1cf38de3e1
Create Date: 2025-12-17 19:58:27.184569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2edd11789cc2'
down_revision = '2e1cf38de3e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('release_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('cost', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_column('cost')
        batch_op.drop_column('release_time')

    # ### end Alembic commands ###
